### ISSUE TITLE
Fix sticky footer using flexbox

### ISSUE THREAD

**Issue by G0dwin** [bikebike/BikeBike#115]
```css
#primary-content {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    overflow: hidden;
}

#main {
    flex: 1;
}
```
