### ISSUE TITLE
Redesign registration steps

### ISSUE THREAD

**Issue by G0dwin** [bikebike/BikeBike#152]
I would like to redesign the registration steps, currently the step links are too large and when there are many of them they may wrap and break the UI.

I think we shuold follow a design similar to this one: https://dribbble.com/shots/611562-Registration-Process

But I think we should have them displayed to the right of the page instead, we may also want to show rotate the text 90deg to save more horizontal space.

**Comment by G0dwin** [comment]
Actually, I like this design better right now: 
![image](https://cloud.githubusercontent.com/assets/1109252/17039578/07334ab2-4f50-11e6-9988-cbe64a475733.png)

Here's some CSS:

```CSS
#new-registration-steps {
    width: 100%;
    display: flex;
    list-style: none;
    text-align: center;
}

#new-registration-steps li {
    flex: 1;
    font-family: "AlteHaasGroteskBold", Helvetica Neue, Helvetica, Arial, Lucida Grande, sans-serif;
}

#new-registration-steps:before {content: '';display: block;width: 100%;flex-basis: 100%;position: absolute;top: 0;border: 0.1em solid #00ADEF;opacity: 0.5;/* border-top-color: #02CA9E; */}

#new-registration-steps li:before {content: '';position: absolute;background-color: #00ADEF;width: 0.5em;height: 0.5em;border-radius: 50%;top: -0.2em;}

#new-registration-steps li.current:before {
    background-color: #EF57B4;
    font-size: 1.5em;
    border: 0.1em solid #00ADEF;
    border-width: 0 0.05em;
}

.step a {
    color: #333;
    opacity: 0.5;
}

.current .step a {
    opacity: 1;
}
```
